# Generated by Django 3.2 on 2021-04-30 00:16

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sourceID',
            field=annoying.fields.AutoOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
        migrations.AddField(
            model_name='post',
            name='sourceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sourceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
        migrations.AddField(
            model_name='project',
            name='sourceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
        migrations.AddField(
            model_name='team',
            name='sourceID',
            field=annoying.fields.AutoOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
    ]
