# Generated by Django 3.2 on 2021-04-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210429_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='_leads_profile_followers_+', to='leads.Source'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='_leads_profile_following_+', to='leads.Source'),
        ),
    ]
