# Generated by Django 3.1.7 on 2021-04-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210420_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experienceFive',
            field=models.TextField(null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experienceFour',
            field=models.TextField(null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experienceOne',
            field=models.TextField(null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experienceThree',
            field=models.TextField(null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experienceTwo',
            field=models.TextField(null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='meetMe',
            field=models.TextField(null=True, verbose_name='Introduce Yourself!'),
        ),
    ]
