# Generated by Django 3.2 on 2021-04-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20210420_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='areaInterestOne',
            field=models.TextField(null=True, verbose_name='What is One of Your Areas of Interest?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='areaInterestThree',
            field=models.TextField(null=True, verbose_name='What is One of Your Areas of Interest?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='areaInterestTwo',
            field=models.TextField(null=True, verbose_name='What is One of Your Areas of Interest?'),
        ),
    ]
