# Generated by Django 3.2 on 2021-04-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20210422_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='uposts',
            name='image',
            field=models.ImageField(height_field=325, null=True, upload_to='pictures/post_pic/', width_field=510),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='user_pro_pic', verbose_name='Profile Picture'),
        ),
    ]
