# Generated by Django 3.2 on 2021-05-04 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20210501_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectTag',
        ),
        migrations.RemoveField(
            model_name='project',
            name='purpose',
        ),
        migrations.AddField(
            model_name='project',
            name='dateFounded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mission',
            field=models.CharField(max_length=50, null=True, verbose_name='What are is this project trying to accomplish?'),
        ),
        migrations.AddField(
            model_name='project',
            name='vision',
            field=models.CharField(max_length=50, null=True, verbose_name="How does your project's application fit in to the future?"),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True, verbose_name='Describe this project.'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('description', models.TextField(null=True, verbose_name='Please describe the role')),
                ('hoursWeek', models.CharField(max_length=50)),
                ('daysWeek', models.CharField(max_length=50, verbose_name='Please describe the average number of work days per week for this role')),
                ('semester', models.CharField(max_length=50, null=True, verbose_name='Please describe the minimum number of semesters for this role')),
                ('qualifications', models.TextField(null=True, verbose_name='What are the basic qualifications for this role')),
                ('niceToHave', models.TextField(null=True, verbose_name='What experience or qualities would be nice to have for this role')),
                ('idealFor', models.TextField(null=True, verbose_name='Who would this role be ideal for')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.project')),
            ],
        ),
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.project')),
            ],
        ),
    ]
