# Generated by Django 3.2.1 on 2021-05-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20210503_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestones',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is this milestone completed yet'),
        ),
    ]
