# Generated by Django 3.2 on 2021-04-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20210422_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uposts',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='goalOneDesc',
            field=models.TextField(null=True, verbose_name='Describe your first research goal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areaInterestOne',
            field=models.TextField(null=True, verbose_name='Please List and Describe Your Area of Interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areaInterestThree',
            field=models.TextField(null=True, verbose_name='Please List and Describe Your Area of Interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areaInterestTwo',
            field=models.TextField(null=True, verbose_name='Please List and Describe Your Area of Interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalThreeDesc',
            field=models.TextField(null=True, verbose_name='Describe your third research goal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalTwoDesc',
            field=models.TextField(null=True, verbose_name='Describe your second research goal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
    ]
