# Generated by Django 3.1.7 on 2021-04-24 22:17

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20210424_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Major',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areaInterestOne',
            field=models.TextField(blank=True, null=True, verbose_name='Please List and Describe Your Area of Interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areaInterestThree',
            field=models.TextField(blank=True, null=True, verbose_name='Please List and Describe Your Area of Interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areaInterestTwo',
            field=models.TextField(blank=True, null=True, verbose_name='Please List and Describe Your Area of Interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experienceFive',
            field=models.TextField(blank=True, null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experienceFour',
            field=models.TextField(blank=True, null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experienceOne',
            field=models.TextField(blank=True, null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experienceThree',
            field=models.TextField(blank=True, null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experienceTwo',
            field=models.TextField(blank=True, null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=models.TextField(blank=True, null=True, verbose_name='Please list Your Areas of Expertise (separate by commas)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalOne',
            field=models.TextField(blank=True, null=True, verbose_name='Please List One of Your Research Goals?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalOneDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Describe your first research goal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalThree',
            field=models.TextField(blank=True, null=True, verbose_name='Please List One of Your Research Goals?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalThreeDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Describe your third research goal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalTwo',
            field=models.TextField(blank=True, null=True, verbose_name='Please List One of Your Research Goals?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalTwoDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Describe your second research goal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.TextField(blank=True, null=True, verbose_name='What Are Your Interests?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lookingFor',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a research team to join.', 'an established Research Team'), ('a project to work on.', 'a fun project to work on'), ('faculty to work under.', 'a faculty mentor'), ('nothing at the moment.', 'nothing at the moment'), ('start project', 'to start a research project'), ('anyone who needs help.', 'the opportunity to help other people however I can'), ('cadets looking to do research for three or four years.', 'cadets interested in research that works towards a scholarship'), ('cadets who want to join a project.', 'cadets who want to join a project'), ('AIADs.', 'AIADs')], max_length=226, null=True, verbose_name='What Are You Currently Looking For?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='meetMe',
            field=models.TextField(blank=True, null=True, verbose_name='Introduce Yourself!'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skillFive',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skillFour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skillOne',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skillThree',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skillTwo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
