# Generated by Django 3.2.1 on 2021-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_club_depclub_uclub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dateFounded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
