# Generated by Django 3.2.1 on 2021-05-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_project_datefounded'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='dateFounded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
