# Generated by Django 3.1.7 on 2021-04-24 22:23

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0009_auto_20210424_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Department',
            field=models.CharField(choices=[('Behavioral Sciences and Leadership', 'Behavioral Sciences and Leadership'), ('Chemistry and Life Science', 'Chemistry and Life Science'), ('Civil and Mechanical Engineering', 'Civil and Mechanical Engineering'), ('Electrical Engineering and Comptuer Science', 'Electrical Engineering and Comptuer Science'), ('English and Philosophy', 'English and Philosophy'), ('Foreign Languages', 'Foreign Languages'), ('Geography and Environmental Engineering', 'Geography and Environmental Engineering'), ('History', 'History'), ('Law', 'Law'), ('Mathematical Sciences', 'Mathematical Sciences'), ('Physics and Nuclear Engineering', 'Physics and Nuclear Engineering'), ('Social Sciences', 'Social Sciences'), ('Systems Engineering', 'Systems Engineering'), ('Independent', 'Independent')], default='Independent', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Major',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Minor',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areaInterestOne',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Please List and Describe Your Area of Interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areaInterestThree',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Please List and Describe Your Area of Interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areaInterestTwo',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Please List and Describe Your Area of Interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='day',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experienceFive',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experienceFour',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experienceOne',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experienceThree',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experienceTwo',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Please List and Describe Your Experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Please list Your Areas of Expertise (separate by commas)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalOne',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Please List One of Your Research Goals?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalOneDesc',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Describe your first research goal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalThree',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Please List One of Your Research Goals?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalThreeDesc',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Describe your third research goal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalTwo',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Please List One of Your Research Goals?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goalTwoDesc',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Describe your second research goal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.TextField(blank=True, default='', null=True, verbose_name='What Are Your Interests?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lookingFor',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a research team to join.', 'an established Research Team'), ('a project to work on.', 'a fun project to work on'), ('faculty to work under.', 'a faculty mentor'), ('nothing at the moment.', 'nothing at the moment'), ('start project', 'to start a research project'), ('anyone who needs help.', 'the opportunity to help other people however I can'), ('cadets looking to do research for three or four years.', 'cadets interested in research that works towards a scholarship'), ('cadets who want to join a project.', 'cadets who want to join a project'), ('AIADs.', 'AIADs')], default='', max_length=226, null=True, verbose_name='What Are You Currently Looking For?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='meetMe',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Introduce Yourself!'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skillFive',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skillFour',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skillOne',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skillThree',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skillTwo',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
