# Generated by Django 3.2 on 2021-04-27 22:37

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0010_auto_20210424_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.department')),
                ('profile', annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.profile')),
                ('project', annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.project')),
                ('team', annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.team')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_ids', models.PositiveIntegerField()),
                ('account_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.source')),
                ('profile', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_ids', models.PositiveIntegerField()),
                ('account_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.source')),
                ('profile', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
