# Generated by Django 3.2.1 on 2021-05-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20210519_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.AlterField(
            model_name='project',
            name='dateFounded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
