# Generated by Django 3.1.7 on 2021-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20210519_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.TextField(blank='', default='', null=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='day',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
