# Generated by Django 3.2.1 on 2021-05-19 18:21

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20210519_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='sourceID',
            field=annoying.fields.AutoOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
        migrations.AddField(
            model_name='source',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.club'),
        ),
    ]
