# Generated by Django 3.1.7 on 2021-05-19 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20210519_1036'),
        ('leads', '0012_auto_20210519_1421'),
    ]

    operations = [
    ]
