# Generated by Django 3.2 on 2021-04-28 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20210427_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.department'),
        ),
        migrations.AlterField(
            model_name='source',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.profile'),
        ),
        migrations.AlterField(
            model_name='source',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.project'),
        ),
        migrations.AlterField(
            model_name='source',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.team'),
        ),
    ]
