# Generated by Django 3.2.1 on 2021-05-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_auto_20210519_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='mission',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
