# Generated by Django 3.2 on 2021-04-28 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='account_types',
        ),
        migrations.RemoveField(
            model_name='following',
            name='profile',
        ),
        migrations.AddField(
            model_name='department',
            name='sourceID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sourceID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
        migrations.AddField(
            model_name='project',
            name='sourceID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='sourceID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='sourceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='department',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.department'),
        ),
        migrations.AlterField(
            model_name='source',
            name='profile',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.profile'),
        ),
        migrations.AlterField(
            model_name='source',
            name='project',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.project'),
        ),
        migrations.AlterField(
            model_name='source',
            name='team',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.team'),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
