# Generated by Django 3.2 on 2021-04-28 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_auto_20210428_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='sourceID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
    ]
