# Generated by Django 3.2 on 2021-04-29 00:16

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_alter_department_sourceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='sourceID',
            field=annoying.fields.AutoOneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.source'),
        ),
    ]
